"""
Utility functions for local_tavily.

This module provides country code normalization and validation utilities
for the Tavily API, which requires full lowercase country names.
"""

from typing import Optional, Set

# Map common ISO-2 / abbreviations -> full country names (lowercase)
COUNTRY_CODE_MAP = {
    # frequently used
    "us": "united states",
    "usa": "united states",
    "uk": "united kingdom",
    "cn": "china",
    "de": "germany",
    "fr": "france",
    "jp": "japan",
    "kr": "south korea",
    "in": "india",
    "br": "brazil",
    "ru": "russia",
    "ca": "canada",
    "au": "australia",
    "mx": "mexico",
    "es": "spain",
    "it": "italy",
    "sg": "singapore",
    "nl": "netherlands",
    "se": "sweden",
    "ch": "switzerland",
    "ae": "united arab emirates",
    "uae": "united arab emirates",
    # extended (non-exhaustive but broad coverage)
    "af": "afghanistan",
    "al": "albania",
    "dz": "algeria",
    "ad": "andorra",
    "ao": "angola",
    "ar": "argentina",
    "am": "armenia",
    "at": "austria",
    "az": "azerbaijan",
    "bs": "bahamas",
    "bh": "bahrain",
    "bd": "bangladesh",
    "bb": "barbados",
    "by": "belarus",
    "be": "belgium",
    "bz": "belize",
    "bj": "benin",
    "bt": "bhutan",
    "bo": "bolivia",
    "ba": "bosnia and herzegovina",
    "bw": "botswana",
    "bn": "brunei",
    "bg": "bulgaria",
    "bf": "burkina faso",
    "bi": "burundi",
    "kh": "cambodia",
    "cm": "cameroon",
    "cv": "cape verde",
    "cf": "central african republic",
    "td": "chad",
    "cl": "chile",
    "co": "colombia",
    "km": "comoros",
    "cg": "congo",
    "cr": "costa rica",
    "hr": "croatia",
    "cu": "cuba",
    "cy": "cyprus",
    "cz": "czech republic",
    "dk": "denmark",
    "dj": "djibouti",
    "do": "dominican republic",
    "ec": "ecuador",
    "eg": "egypt",
    "sv": "el salvador",
    "gq": "equatorial guinea",
    "er": "eritrea",
    "ee": "estonia",
    "et": "ethiopia",
    "fj": "fiji",
    "fi": "finland",
    "ga": "gabon",
    "gm": "gambia",
    "ge": "georgia",
    "gh": "ghana",
    "gr": "greece",
    "gt": "guatemala",
    "gn": "guinea",
    "ht": "haiti",
    "hn": "honduras",
    "hu": "hungary",
    "is": "iceland",
    "id": "indonesia",
    "ir": "iran",
    "iq": "iraq",
    "ie": "ireland",
    "il": "israel",
    "jm": "jamaica",
    "jo": "jordan",
    "kz": "kazakhstan",
    "ke": "kenya",
    "kw": "kuwait",
    "kg": "kyrgyzstan",
    "lv": "latvia",
    "lb": "lebanon",
    "ls": "lesotho",
    "lr": "liberia",
    "ly": "libya",
    "li": "liechtenstein",
    "lt": "lithuania",
    "lu": "luxembourg",
    "mg": "madagascar",
    "mw": "malawi",
    "my": "malaysia",
    "mv": "maldives",
    "ml": "mali",
    "mt": "malta",
    "mr": "mauritania",
    "mu": "mauritius",
    "md": "moldova",
    "mc": "monaco",
    "mn": "mongolia",
    "me": "montenegro",
    "ma": "morocco",
    "mz": "mozambique",
    "mm": "myanmar",
    "na": "namibia",
    "np": "nepal",
    "nz": "new zealand",
    "ni": "nicaragua",
    "ne": "niger",
    "ng": "nigeria",
    "kp": "north korea",
    "mk": "north macedonia",
    "no": "norway",
    "om": "oman",
    "pk": "pakistan",
    "pa": "panama",
    "pg": "papua new guinea",
    "py": "paraguay",
    "pe": "peru",
    "ph": "philippines",
    "pl": "poland",
    "pt": "portugal",
    "qa": "qatar",
    "ro": "romania",
    "rw": "rwanda",
    "sa": "saudi arabia",
    "sn": "senegal",
    "rs": "serbia",
    "sk": "slovakia",
    "si": "slovenia",
    "so": "somalia",
    "za": "south africa",
    "ss": "south sudan",
    "lk": "sri lanka",
    "sd": "sudan",
    "tw": "taiwan",
    "tj": "tajikistan",
    "tz": "tanzania",
    "th": "thailand",
    "tg": "togo",
    "tt": "trinidad and tobago",
    "tn": "tunisia",
    "tr": "turkey",
    "tm": "turkmenistan",
    "ug": "uganda",
    "ua": "ukraine",
    "ae2": "united arab emirates",  # safeguard
    "gb": "united kingdom",
    "uy": "uruguay",
    "uz": "uzbekistan",
    "ve": "venezuela",
    "vn": "vietnam",
    "ye": "yemen",
    "zm": "zambia",
    "zw": "zimbabwe",
}

# Valid Tavily country names (lowercase) from API reference
VALID_TAVILY_COUNTRIES: Set[str] = {
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "argentina",
    "armenia",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bhutan",
    "bolivia",
    "bosnia and herzegovina",
    "botswana",
    "brazil",
    "brunei",
    "bulgaria",
    "burkina faso",
    "burundi",
    "cambodia",
    "cameroon",
    "canada",
    "cape verde",
    "central african republic",
    "chad",
    "chile",
    "china",
    "colombia",
    "comoros",
    "congo",
    "costa rica",
    "croatia",
    "cuba",
    "cyprus",
    "czech republic",
    "denmark",
    "djibouti",
    "dominican republic",
    "ecuador",
    "egypt",
    "el salvador",
    "equatorial guinea",
    "eritrea",
    "estonia",
    "ethiopia",
    "fiji",
    "finland",
    "france",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "greece",
    "guatemala",
    "guinea",
    "haiti",
    "honduras",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "israel",
    "italy",
    "jamaica",
    "japan",
    "jordan",
    "kazakhstan",
    "kenya",
    "kuwait",
    "kyrgyzstan",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "mauritania",
    "mauritius",
    "mexico",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nepal",
    "netherlands",
    "new zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "north korea",
    "north macedonia",
    "norway",
    "oman",
    "pakistan",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "qatar",
    "romania",
    "russia",
    "rwanda",
    "saudi arabia",
    "senegal",
    "serbia",
    "singapore",
    "slovakia",
    "slovenia",
    "somalia",
    "south africa",
    "south korea",
    "south sudan",
    "spain",
    "sri lanka",
    "sudan",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "togo",
    "trinidad and tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united states",
    "uruguay",
    "uzbekistan",
    "venezuela",
    "vietnam",
    "yemen",
    "zambia",
    "zimbabwe",
}


def normalize_country(raw_country: Optional[str]) -> Optional[str]:
    """
    Normalize user-provided country to Tavily's expected enum value (lowercase full name).

    Tavily requires full, lowercased country names as enumerated values (e.g.,
    "united states", "united kingdom"). Users often provide ISO2 codes like
    "us", "uk" or common abbreviations like "uae". This function normalizes
    such inputs to Tavily's expected values.

    Args:
        raw_country: The country string provided by the user, which may be
                     a full name, ISO code, or abbreviation.

    Returns:
        The normalized country name (lowercase) or None if input is falsy.

    Raises:
        ValueError: If the country cannot be normalized to a valid Tavily country.

    Examples:
        >>> normalize_country("US")
        "united states"
        >>> normalize_country("United Kingdom")
        "united kingdom"
        >>> normalize_country(None)
        None
    """
    if not raw_country:
        return None
    candidate = str(raw_country).strip().lower()

    # direct match of full name
    if candidate in VALID_TAVILY_COUNTRIES:
        return candidate

    # map common codes/abbreviations
    if candidate in COUNTRY_CODE_MAP:
        normalized = COUNTRY_CODE_MAP[candidate]
        if normalized in VALID_TAVILY_COUNTRIES:
            return normalized

    # last chance: remove periods from abbreviations like "u.s." -> "us"
    simplified = candidate.replace(".", "")
    if simplified in COUNTRY_CODE_MAP:
        normalized = COUNTRY_CODE_MAP[simplified]
        if normalized in VALID_TAVILY_COUNTRIES:
            return normalized

    raise ValueError(
        f"Invalid country '{raw_country}'. Provide a full country name (e.g., 'united states') "
        f"or ISO code like 'us', 'uk', 'cn'."
    )
